name: Error1

# Contrôler quand le workflow va s’exécuter
on:
  # Déclenche le workflow quand il y a un push ou un pull request sur la branche “main”
    push:
        branches: 
        - "main"
    pull_request:
        branches:
        - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, ${{ inputs.username }}! 
